language: Crystal

sudo: required

os: linux

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

compiler:
  - gcc

before_install:
  - eval "${MATRIX_EVAL}"

script:
 - "./install.sh"

branches:
  only:
    - master
    - /^feature\//
    - /^bug\//