language: Crystal

sudo: required

compiler:
  - crystal

before_install:
  - sudo apt-get install gcc

os:
  - linux

script:
 - "./install.sh"

branches:
  only:
    - master
    - /^feature\//
    - /^bug\//