language: Crystal

sudo: required

os: linux

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

compiler:
  - gcc

before_install:
  - sudo apt-get install gcc-6

  - sudo rm /usr/bin/gcc
  - sudo rm /usr/bin/g++

  - sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/bin/g++

  - gcc -v

script:
 - "./install.sh"

branches:
  only:
    - master
    - /^feature\//
    - /^bug\//