language: crystal

sudo: required

os: linux

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

compiler:
  - gcc

before_install:
  - sudo apt-get update
  
  - sudo rm /usr/bin/gcc
  - sudo rm /usr/bin/g++

  - sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/bin/g++

  - gcc -v
  - wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz
  - tar xzf gsl-2.4.tar.gz
  - cd gsl-2.4
  - ./configure
  - make && sudo make install
  - cd ..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - export CFLAGS="-I/usr/local/include"
  - export LDFLAGS="-L/usr/local/lib"
  - sudo apt-get install python3.5-dev

  - if [ ! -d "./bin" ]; then
      mkdir ./bin; 
    fi
  - if [ ! -d "/usr/local/lib/LinCAS/LinCAS" ]; then
      sudo mkdir -p /usr/local/lib/LinCAS/LinCAS;
    fi 
  - if [ ! -d "/usr/local/lib/LinCAS/lib" ]; then
      sudo mkdir -p /usr/local/lib/LinCAS/lib;
    fi

script: 
  - gcc -c -o ./src/Internal/LibC/libc.o ./src/Internal/LibC/libc.c
  - ar rcs ./src/Internal/LibC/libc.a ./src/Internal/LibC/libc.o
  - crystal build ./src/LinCAS.cr -o ./bin/lincas --no-debug --release --stats
  - ls ./bin
  - sudo cp ./bin/lincas /usr/bin/lincas
  - sudo touch /usr/local/lib/LinCAS/LinCAS/VERSION
  - sudo cp ./VERSION /usr/local/lib/LinCAS/LinCAS/VERSION
  - sudo cp -r ./lib/test /usr/local/lib/LinCAS/lib
  - crystal spec


branches:
  only:
    - master
    - /^feature\//
    - /^bug\//
    - lincas_0_0_1

    