language: Crystal

sudo: required

os: linux

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

compiler:
  - gcc

before_install:
  - sudo apt-get install gcc-5
  - gcc=gcc-6
  - gcc -v

script:
 - "./install.sh"

branches:
  only:
    - master
    - /^feature\//
    - /^bug\//